/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial2;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolax
 */
public class FrmProducto extends javax.swing.JFrame {
    
    private static ArrayList<Electrodomestico> electrodomesticos = new ArrayList();
    private static ArrayList<LineaBlanca> productosLb = new ArrayList();
    private static String codigoP;
    String clave1 =("LBl"), clave2 = ("Ele");
    public static int cantidadE, cantidadLb;
    /**
     * Creates new form FrmElectrodomestico
     */
    public FrmProducto(ArrayList<LineaBlanca> productoLb, ArrayList<Electrodomestico> electrodomestico, String codigoP) {
        initComponents();
        this.electrodomesticos = electrodomestico;
        this.productosLb = productoLb;
        this.codigoP = codigoP;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        rbLineaBlanca = new javax.swing.JRadioButton();
        rbElectrodomestico = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInv = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Linea:");

        buttonGroup1.add(rbLineaBlanca);
        rbLineaBlanca.setText("Linea Blanca");

        buttonGroup1.add(rbElectrodomestico);
        rbElectrodomestico.setSelected(true);
        rbElectrodomestico.setText("Electrodomestico");

        jLabel4.setText("Codgio");

        txtInv.setEditable(false);
        jScrollPane1.setViewportView(txtInv);

        jLabel5.setText("Inv.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbElectrodomestico)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbLineaBlanca))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbElectrodomestico)
                            .addComponent(rbLineaBlanca)))))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(bEliminar)
                    .addComponent(bBuscar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     boolean linea = false;
     boolean encontrado = false;
     if(rbElectrodomestico.isSelected() && !rbLineaBlanca.isSelected()){
         linea = true;
         cantidadE++;
         codigoP =("Ele"+txtCodigo);
         Electrodomestico nuevoElectrodomestico = new Electrodomestico("Ele"+txtCodigo.getText(),cantidadE, txtNombre.getText(),Double.parseDouble(txtPrecio.getText()),linea);
         
         for(int i=0; i<electrodomesticos.size();i++){
             if(electrodomesticos.get(i).getCodProducto().equals(nuevoElectrodomestico.getCodProducto())){
                 electrodomesticos.set(1,nuevoElectrodomestico);
                 encontrado = true;
                 break;
             }
         }
         electrodomesticos.add(nuevoElectrodomestico);       
     }else if(!rbElectrodomestico.isSelected() && rbLineaBlanca.isSelected()){
         linea = false;
                  cantidadLb++;
              codigoP =("LBl"+txtCodigo);
         LineaBlanca nuevoLineaBl = new LineaBlanca("LBl"+txtCodigo.getText(),cantidadLb,txtNombre.getText(),Double.parseDouble(txtPrecio.getText()),linea);
          for(int i=0; i<productosLb.size();i++){
             if(productosLb.get(i).getCodProducto().equals(nuevoLineaBl.getCodProducto())){
                 productosLb.set(1,nuevoLineaBl);
                 encontrado = true;
                 break;
             }
           }
        productosLb.add(nuevoLineaBl);
     }
    
     if(encontrado){
         JOptionPane.showMessageDialog(this," Producto se a modificado","Modificar Producto", JOptionPane.INFORMATION_MESSAGE);
     }else{
         JOptionPane.showMessageDialog(this," Producto insertado", "Nuevo Producto",JOptionPane.INFORMATION_MESSAGE);

     }
     limpiarCampos();
    System.out.println(Arrays.asList(electrodomesticos));
    System.out.println(Arrays.asList(productosLb));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     Inventario inventario= new Inventario(productosLb,electrodomesticos);
     inventario.setVisible(true);
     
    }//GEN-LAST:event_formWindowClosing

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        boolean encontrado = false;
    codigoP = txtCodigo.getText();  
    
    for(int i=0;i<3;i++){
    if(codigoP.charAt(i)!=clave1.charAt(i)){
          if(codigoP.charAt(i)!=clave2.charAt(i)){
            JOptionPane.showMessageDialog(this, "Código Invalido, verificalo.","Busqueda Producto",JOptionPane.WARNING_MESSAGE);
            limpiarCampos();
        }else{
          if(codigoP.charAt(i)==clave1.charAt(i)){
              for(LineaBlanca productoLb: productosLb){
              if(productoLb.getCodProducto().equals(txtCodigo.getText())){
                  txtCodigo.setText(productoLb.getCodProducto());
                  txtInv.setText(Integer.toString(productoLb.getCantidad()));
                  txtNombre.setText(productoLb.getNombrePro());
                  txtPrecio.setText(String.valueOf(productoLb.getPrecio()));
                  rbLineaBlanca.setSelected(true);
                  rbElectrodomestico.setSelected(false);
                }
                encontrado = true;
                break;
              }
            }else{
              for(Electrodomestico electrodomestico: electrodomesticos){
              if(electrodomestico.getCodProducto().equals(txtCodigo.getText())){
                  txtCodigo.setText(electrodomestico.getCodProducto());
                  txtInv.setText(Integer.toString(electrodomestico.getCantidad()));
                  txtNombre.setText(electrodomestico.getNombrePro());
                  txtPrecio.setText(String.valueOf(electrodomestico.getPrecio()));
                  rbLineaBlanca.setSelected(false);
                  rbElectrodomestico.setSelected(true);
                }
                encontrado = true;
                break;
              }    
            }
          } 
        }  
    }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
    boolean encontrado = false;
    for(int i=0;i<3;i++){
        if(codigoP.charAt(i)!=clave1.charAt(i)){
             if(codigoP.charAt(i)!=clave2.charAt(i)){
              JOptionPane.showMessageDialog(this, "Código Invalido, verificalo.","Busqueda Producto",JOptionPane.WARNING_MESSAGE);
              limpiarCampos();
            }else{
                 if(codigoP.charAt(i)==clave1.charAt(i)){
                    for(LineaBlanca productoLb: productosLb){
                        if(productoLb.getCodProducto().equals(txtCodigo.getText())){
                            productosLb.remove(productoLb);
                            encontrado = true;
                            JOptionPane.showMessageDialog(this," Producto eliminado correctamente","Eliminar Producto",JOptionPane.INFORMATION_MESSAGE);
                            limpiarCampos();
                            break;
                            }
                    }
            
                 }else{
                        for(Electrodomestico electrodomestico: electrodomesticos){
                        if(electrodomestico.getCodProducto().equals(txtCodigo.getText())){
                            electrodomesticos.remove(electrodomestico);
                            encontrado = true;
                            JOptionPane.showMessageDialog(this," Producto eliminado correctamente","Eliminar Producto",JOptionPane.INFORMATION_MESSAGE);
                            limpiarCampos();
                            break;
                            }
                        }
                    }
                }
        }
    }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void limpiarCampos(){
    txtCodigo.setText("");
    txtInv.setText("");
    txtNombre.setText("");
    txtPrecio.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto(productosLb,electrodomesticos,codigoP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbElectrodomestico;
    private javax.swing.JRadioButton rbLineaBlanca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextPane txtInv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
